logging:
  config: classpath:log/logback.xml
  level:
    com.netflix.discovery.DiscoveryClient: WARN
server:  
  #端口，必须
  port: 8080  
  #执行路径，必须
  servlet:
    context-path: /
  #网络协议
#  protocol: http
  #执行的域名，必须
  domain: localhost
#  followContextPath: true
  devMode: true
  error:
    path: /error
    include-stacktrace: always
    whitelabel:
      enabled: false
imageServer:
  host: localhost
uploadServer:
  host: localhost
staticServer:
  host: localhost,127.0.0.1
testServer:
  host: 127.0.0.1
  port: 8080
melos:
  connection:
    maxTotal: 100
    maxPerRoute: 10
    socketTimeOut: 3000
    connectionTimeOut: 3000
    connectionRequestTimeOut: 5000
  web: 
    meta:
      cookie:
        name: _h_
        maxCount: 20
        maxLength: 4095
        domain: localhost
        path: /
    encoding: utf-8
    monitor:
      threshold: 100
    locale:
      cookieName: _l_
      support: zh_CN,en_US
      default: zh_CN

      country: true
      language: true
spring:  
  mvc:
    static-path-pattern: /**
    favicon:
      enabled: false
  resources:
    static-locations:  classpath:/static/
  thymeleaf:  
    cache: false
    prefix: classpath:/templates/
    suffix: .htm
    encoding: utf-8
    content-type: text/html
    mode: HTML5
  redis:
    database: 5  
    host: 127.0.0.1
    port: 6379
    password:  123456
    pool:
      max-active: 1000
      max-wait: -1 
      max-idle: 100  
      min-idle: 0  
    timeout: 30000  
  datasource:
    password: abc123
    username: root
    url: jdbc:mysql://localhost:3306/mysql?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始连接数
      initial-size: 5
      # 最大激活数
      max-active: 50
      # 最大等待时间
      max-wait: 3000
      # 是否启用非公平锁
      use-unfair-lock: true
      # mysql 用 false | oracle 用 true
      pool-prepared-statements: false
      # 启动监听、日志、防注入的功能
      filters: stat,log4j,wall
      # 验证的sql语句
      validation-query: select 1
      # 验证超时
      validation-query-timeout: 3000
      # 连接时是否开启验证
      test-on-borrow: true
      # 退还连接时是否开启验证
      test-on-return: false
      # 建议配置为true，不影响性能，并且保证安全性
      test-while-idle: true
      # Destroy线程会检测连接的间隔时间 || testWhileIdle的判断依据
      time-between-eviction-runs-millis: 5000
  http:
    multipart:
      maxFileSize: 50Mb
      maxRequestSize: 50Mb